### ISSUE TITLE
After host update 5.0.2 no connect and crashes

### ISSUE THREAD

**Issue by lhoem** [foxriver76/ioBroker.denon#319]
Hello,

after the host update to 5.0.2 the adapter won't start:

denon.0 2023-06-12 14:19:19.369	warn	Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
denon.0 2023-06-12 14:19:19.251	error	adapter disabled
denon.0 2023-06-12 14:18:47.682	info	terminating
denon.0 2023-06-12 14:18:47.181	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
denon.0 2023-06-12 14:18:47.180	info	terminating
denon.0 2023-06-12 14:18:47.179	info	[END] Stopping Denon AVR adapter...
denon.0 2023-06-12 14:18:47.175	error	undefined is not a valid state value
denon.0 2023-06-12 14:18:47.175	error	Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at Denon._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5372:49) at Denon.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5333:21) at Denon.handleResponse (/opt/iobroker/node_modules/iobroker.denon/build/main.js:1602:18)
denon.0 2023-06-12 14:18:47.172	error	unhandled promise rejection: undefined is not a valid state value
denon.0 2023-06-12 14:18:47.171	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
denon.0 2023-06-12 14:18:42.906	info	[CONNECT] Adapter connected to DENON-AVR: 192.168.188.223:23
denon.0 2023-06-12 14:18:42.892	info	[CONNECT] Trying to connect to 192.168.188.223:23
denon.0 2023-06-12 14:18:42.890	info	[START] Starting DENON AVR adapter
denon.0 2023-06-12 14:18:42.870	info	starting. Version 1.15.1 in /opt/iobroker/node_modules/iobroker.denon, node: v16.19.1, js-controller: 5.0.2

**Versions:**
 - Adapter version: 1.15.1
 - JS-Controller version: 7.0.5 
 - Node version: 16.19.1
 - Operating system: ubuntu
 - AVR model: Denon AVR-X3500H

What can it be?

Regards
Lothar

**Comment by foxriver76** [comment]
It seems like the picture mode cannot be decoded and we end up setting `undefined`

**Comment by lhoem** [comment]
What should I do? Restarting the device and iobroker did not eliminate the problem

**Comment by lhoem** [comment]
Great! I will wait and test then

**Comment by foxriver76** [comment]
Please test 1.15.2

And if you set the adapter to debug, you will probably find a line `Unknown picture mode: "${pictureMode}"`. It would be great if you can provide me the information, would be interesting if it is a whole different command which I need to distinguish or just a new picture mode.

**Comment by foxriver76** [comment]
No, you can change the loglevel of the instance in admin "tab instances" (click on the head icon in the top menu bar to activate expert mode), then you can change the loglevel when clicking on the denon adapter.

**Comment by lhoem** [comment]
yes, I do this before I wrote. This is I got;

<html>
<body>


denon.0 | 2023-06-12 21:18:38.510 | debug | [INFO] ==> Message sent: BDSTATUS?
-- | -- | -- | --
denon.0 | 2023-06-12 21:18:38.409 | debug | [INFO] ==> Message sent: Z3SMART ?
denon.0 | 2023-06-12 21:18:38.308 | debug | [INFO] ==> Message sent: Z2SMART ?
denon.0 | 2023-06-12 21:18:38.207 | debug | [INFO] ==> Message sent: Z3QUICK ?
denon.0 | 2023-06-12 21:18:38.143 | debug | [DATA] <== Incoming data: Z2QUICK0
denon.0 | 2023-06-12 21:18:38.106 | debug | [INFO] ==> Message sent: Z2QUICK ?
denon.0 | 2023-06-12 21:18:38.006 | debug | [INFO] ==> Message sent: PR00TR?
denon.0 | 2023-06-12 21:18:37.905 | debug | [INFO] ==> Message sent: MSSMART ?
denon.0 | 2023-06-12 21:18:37.873 | debug | [DATA] <== Incoming data: MSQUICK2
denon.0 | 2023-06-12 21:18:37.804 | debug | [INFO] ==> Message sent: MSQUICK ?
denon.0 | 2023-06-12 21:18:37.702 | debug | [INFO] ==> Message sent: Z3SLP?
denon.0 | 2023-06-12 21:18:37.637 | debug | [INFO] <== Command to handle is ZSLPOFF
denon.0 | 2023-06-12 21:18:37.633 | debug | [DATA] <== Incoming data: Z2SLPOFF
denon.0 | 2023-06-12 21:18:37.602 | debug | [INFO] ==> Message sent: Z2SLP?
denon.0 | 2023-06-12 21:18:37.559 | debug | [INFO] <== Command to handle is SLPOFF
denon.0 | 2023-06-12 21:18:37.557 | debug | [DATA] <== Incoming data: SLPOFF
denon.0 | 2023-06-12 21:18:37.502 | debug | [INFO] ==> Message sent: SLP?
denon.0 | 2023-06-12 21:18:37.400 | debug | [INFO] ==> Message sent: NSE


</body>
</html>
There are no other messages...
