### ISSUE TITLE
Adapter restarts after update js-controller 3.0

### ISSUE THREAD

**Issue by ReaverPhoenix** [foxriver76/ioBroker.denon#74]
After the js-controller 3.0 update the adapter restarts in a loop. The other adapters are workin' well.

```
2020-04-21 19:16:32.075 - info: host.orangepiplus instance system.adapter.denon.0 started with pid 5253
2020-04-21 19:16:35.745 - info: denon.0 (5253) starting. Version 1.7.4 in /opt/iobroker/node_modules/iobroker.denon, node: v10.20.1, js-controller: 3.0.14
2020-04-21 19:16:35.838 - info: denon.0 (5253) [START] Starting DENON AVR adapter
2020-04-21 19:16:35.854 - info: denon.0 (5253) [CONNECT] Trying to connect to 192.168.178.31:23
2020-04-21 19:16:35.923 - info: denon.0 (5253) [CONNECT] Adapter connected to DENON-AVR: 192.168.178.31:23
2020-04-21 19:16:36.178 - error: denon.0 (5253) uncaught exception: The id is empty! Please provide a valid id.
2020-04-21 19:16:36.188 - error: denon.0 (5253) Error: The id is empty! Please provide a valid id.
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1570:39
at Immediate.callback.function.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3109:70)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
2020-04-21 19:16:36.193 - info: denon.0 (5253) [END] Stopping Denon AVR adapter...
2020-04-21 19:16:36.369 - info: denon.0 (5253) terminating
2020-04-21 19:16:36.374 - info: denon.0 (5253) Terminated (NO_ERROR): Without reason
2020-04-21 19:16:36.494 - warn: denon.0 (5253) Connection closed: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
2020-04-21 19:16:36.907 - info: host.orangepiplus instance system.adapter.denon.0 terminated with code 0 (NO_ERROR)
2020-04-21 19:16:36.910 - info: host.orangepiplus Restart adapter system.adapter.denon.0 because enabled
```
Cheers
Reaver

**Comment by foxriver76** [comment]
Will test later thanks for reporting

**Comment by foxriver76** [comment]
Hm according to the log, it has to be a setObjectNotExists call, however I checked all and we are never providing an empty id.. strange. Also, I am not able to reproduce it adapter 1.7.4 + js-c 3.0.14. Can change log level to debug and post the log, please?

**Comment by ReaverPhoenix** [comment]
Klar, das kann ich  gern machen :) Hatte gerade mitbekommen, dass ich ja auch auf deutsch schreiben kann. :)
```

2020-04-21 22:49:20.139  - info: host.orangepiplus instance system.adapter.denon.0 started with pid 12070
--
2020-04-21 22:49:22.451  - debug: denon.0 (12070) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-04-21 22:49:22.551  - debug: denon.0 (12070) Objects client ready ... initialize now
2020-04-21 22:49:22.564  - debug: denon.0 (12070) Objects create System PubSub Client
2020-04-21 22:49:22.567  - debug: denon.0 (12070) Objects create User PubSub Client
2020-04-21 22:49:22.570  - debug: denon.0 (12070) Objects client initialize lua scripts
2020-04-21 22:49:22.602  - debug: denon.0 (12070) Objects connected to redis: 127.0.0.1:9001
2020-04-21 22:49:22.623  - debug: denon.0 (12070) objectDB connected
2020-04-21 22:49:22.631  - debug: denon.0 (12070) Redis States: Use Redis connection: 127.0.0.1:9000
2020-04-21 22:49:22.646  - debug: denon.0 (12070) States create User PubSub Client
2020-04-21 22:49:22.653  - debug: denon.0 (12070) States create System PubSub Client
2020-04-21 22:49:22.672  - debug: denon.0 (12070) States connected to redis: 127.0.0.1:9000
2020-04-21 22:49:22.675  - debug: denon.0 (12070) statesDB connected
2020-04-21 22:49:23.484  - info: denon.0 (12070) starting. Version 1.7.4 in /opt/iobroker/node_modules/iobroker.denon, node: v10.20.1, js-controller: 3.0.14
2020-04-21 22:49:23.544  - info: denon.0 (12070) [START] Starting DENON AVR adapter
2020-04-21 22:49:23.549  - info: denon.0 (12070) [CONNECT] Trying to connect to 192.168.178.31:23
2020-04-21 22:49:23.602  - info: denon.0 (12070) [CONNECT] Adapter connected to DENON-AVR: 192.168.178.31:23
2020-04-21 22:49:23.604  - debug: denon.0 (12070) [CONNECT] Connected --> Check receiver type
2020-04-21 22:49:23.606  - debug: denon.0 (12070) [INFO] ==> Message sent: SV?
2020-04-21 22:49:23.609  - debug: denon.0 (12070) [INFO] ==> Message sent: SV01?
2020-04-21 22:49:23.610  - debug: denon.0 (12070) [INFO] ==> Message sent: BDSTATUS?
2020-04-21 22:49:23.612  - debug: denon.0 (12070) [INFO] ==> Message sent: MV?
2020-04-21 22:49:23.655  - debug: denon.0 (12070) [DATA] <== Incoming data: SVSOURCE
2020-04-21 22:49:23.668  - debug: denon.0 (12070) [DATA] <== Incoming data: MV36
2020-04-21 22:49:23.733  - error: denon.0 (12070) uncaught exception: The id is empty! Please provide a valid id.
2020-04-21 22:49:23.741  - error: denon.0 (12070) Error: The id is empty! Please provide a valid id.
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1570:39
at Immediate.callback.function.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3109:70)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
2020-04-21 22:49:23.745  - info: denon.0 (12070) [END] Stopping Denon AVR adapter...
2020-04-21 22:49:23.786  - debug: denon.0 (12070) [INFO] DE states created
2020-04-21 22:49:23.788  - debug: denon.0 (12070) [UPDATE] Updating states
2020-04-21 22:49:23.797  - info: denon.0 (12070) terminating
2020-04-21 22:49:23.802  - info: denon.0 (12070) Terminated (NO_ERROR): Without reason
2020-04-21 22:49:23.897  - warn: denon.0 (12070) Connection closed: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
2020-04-21 22:49:23.899  - debug: denon.0 (12070) [INFO] ==> Message sent: NSET1 ?
2020-04-21 22:49:23.992  - debug: denon.0 (12070) [INFO] ==> Message sent: NSFRN ?
2020-04-21 22:49:24.093  - debug: denon.0 (12070) [INFO] ==> Message sent: ZM?
2020-04-21 22:49:24.194  - debug: denon.0 (12070) [INFO] ==> Message sent: MU?
2020-04-21 22:49:24.294  - debug: denon.0 (12070) [INFO] ==> Message sent: PW?
2020-04-21 22:49:24.333  - info: host.orangepiplus instance system.adapter.denon.0 terminated with code 0 (NO_ERROR)
2020-04-21 22:49:24.334  - info: host.orangepiplus Restart adapter system.adapter.denon.0 because enabled
```

**Comment by foxriver76** [comment]
Ne hat damit nix zu tun, update mal bitte Denon auf die 1.7.5 sobald sie dir angezeigt wird.

**Comment by ReaverPhoenix** [comment]
Okay, ich konnte das Problem, indem ich den AVR für einige Sekunden komplett von der Stromversorgung genommen habe. Im Anschluss hat der Adapter alle States abgerufen und ist nun aktiv.

Ich danke dir für deine Bemühungen <3

Liebe Grüße

**Comment by foxriver76** [comment]
Gerne. 1.7.5 sollte sowas auch genauer loggen und zumindest einen Crash verhindern.
